# Generated by Django 5.2.1 on 2025-07-11 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteinventario',
            name='cuenta_credito',
            field=models.IntegerField(default=1010900, verbose_name='Cuenta Crédito'),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='cuenta_debito',
            field=models.IntegerField(default=3020900, verbose_name='Cuenta Débito'),
        ),
        migrations.AlterField(
            model_name='asientoscontables',
            name='credito',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='asientoscontables',
            name='cuenta_debito',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='La cuenta débito debe tener exactamente 7 dígitos.', regex='^\\d{7}$')], verbose_name='Cuenta Débito'),
        ),
        migrations.AlterField(
            model_name='asientoscontables',
            name='debito',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Débito'),
        ),
        migrations.AlterField(
            model_name='balanceinicial',
            name='cuenta_credito',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito'),
        ),
        migrations.AlterField(
            model_name='balanceinicial',
            name='cuenta_debito',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito'),
        ),
        migrations.AlterField(
            model_name='otrosgastos',
            name='cuenta_credito',
            field=models.CharField(default=1010100, max_length=7, validators=[django.core.validators.RegexValidator(message='La cuenta crédito debe tener exactamente 7 dígitos.', regex='^\\d{7}$')], verbose_name='Cuenta Crédito'),
        ),
        migrations.AlterField(
            model_name='otrosgastos',
            name='cuenta_debito',
            field=models.CharField(default=1011001, max_length=7, validators=[django.core.validators.RegexValidator(message='La cuenta débito debe tener exactamente 7 dígitos.', regex='^\\d{7}$')], verbose_name='Cuenta Débito'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='credito2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito 2'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Débito'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_credito',
            field=models.IntegerField(default=3010101, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_credito_eerr',
            field=models.IntegerField(default=3010101, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito EERR'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_credito_envio',
            field=models.IntegerField(default=3010111, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito Envío'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_credito_existencia',
            field=models.IntegerField(default=1010900, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito Existencia'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_debito_costo',
            field=models.IntegerField(default=3010200, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito Costo'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_debito_envio',
            field=models.IntegerField(default=1010100, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito Envío'),
        ),
    ]
