# Generated by Django 5.2.1 on 2025-07-11 21:29

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0002_alter_ajusteinventario_cuenta_credito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sueldoshonorarios',
            name='fecha',
        ),
        migrations.AddField(
            model_name='sueldoshonorarios',
            name='echa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='credito2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Crédito 2'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='cuenta_credito',
            field=models.IntegerField(default=1010100, editable=False, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='cuenta_credito2',
            field=models.IntegerField(default=2011200, editable=False, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito 2'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='cuenta_debito',
            field=models.IntegerField(default=3010300, editable=False, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito'),
        ),
        migrations.AlterField(
            model_name='sueldoshonorarios',
            name='debito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Débito'),
        ),
    ]
