# Generated by Django 5.2.1 on 2025-07-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0003_remove_sueldoshonorarios_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sueldoshonorarios',
            old_name='echa',
            new_name='fecha',
        ),
    ]
