# Generated by Django 5.2.1 on 2025-07-11 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0004_rename_echa_sueldoshonorarios_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_credito',
            field=models.IntegerField(default=1010900, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_debito_eerr',
            field=models.IntegerField(default=3010200, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito EERR'),
        ),
    ]
