# Generated by Django 5.2.1 on 2025-07-11 22:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0005_alter_ventas_cuenta_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproductos',
            name='costo_con_iva',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=1, verbose_name='Costo con IVA'),
        ),
        migrations.AlterField(
            model_name='entradaproductos',
            name='costo_neto',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, max_digits=14, verbose_name='Costo Neto'),
        ),
        migrations.AlterField(
            model_name='entradaproductos',
            name='costo_total',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, max_digits=14, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='entradaproductos',
            name='costo_unitario_total_producto',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, max_digits=12, verbose_name='Costo Unitario Total Producto'),
        ),
        migrations.AlterField(
            model_name='entradaproductos',
            name='iva_compra',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, max_digits=12, verbose_name='IVA Compra'),
        ),
    ]
