# Generated by Django 5.2.1 on 2025-07-11 23:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0006_alter_entradaproductos_costo_con_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproductos',
            name='costo_con_iva',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=12, verbose_name='Costo con IVA'),
        ),
    ]
