# Generated by Django 5.2.1 on 2025-07-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0007_alter_entradaproductos_costo_con_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(unique=True)),
                ('ventas', models.DecimalField(decimal_places=2, max_digits=18)),
                ('costos', models.DecimalField(decimal_places=2, max_digits=18)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('margen_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('otros', models.TextField(blank=True, default='')),
            ],
        ),
    ]
