# Generated by Django 5.2.1 on 2025-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0008_resumenmensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenmensual',
            name='utilidad_acumulada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
