# Generated by Django 5.2.1 on 2025-07-27 16:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0009_resumenmensual_utilidad_acumulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='credito_plataformas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Crédito Plataforma'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cuenta_debito_iva_plataformas',
            field=models.IntegerField(default=1011001, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito IVA Plataforma'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='debito_iva_plataformas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Débito IVA Plataforma'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='debito_plataformas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Débito Plataforma'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='comision_plataformas_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Comisión Plataforma Pago'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_credito_plataformas',
            field=models.IntegerField(default=1010100, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Crédito Plataforma'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_debito_plataformas',
            field=models.IntegerField(default=3020200, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito Plataforma'),
        ),
    ]
