# Generated by Django 5.2.1 on 2025-07-27 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0010_ventas_credito_plataformas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cuenta_debito_plataformas',
            field=models.IntegerField(default=3010212, validators=[django.core.validators.MinValueValidator(1000000, message='La cuenta debe tener exactamente 7 dígitos.'), django.core.validators.MaxValueValidator(9999999, message='La cuenta debe tener exactamente 7 dígitos.')], verbose_name='Cuenta Débito Plataforma'),
        ),
    ]
