# Generated by Django 5.2.1 on 2025-07-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0011_alter_ventas_cuenta_debito_plataformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoMensualDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('concepto', models.CharField(choices=[('ventas', 'Ventas'), ('costo_venta', 'Costo de Venta'), ('gastos_comercializacion', 'Gastos de Comercialización'), ('gastos_marketing', 'Gastos Publicidad y Marketing'), ('gastos_arriendos', 'Gastos arriendos Comisiones Tiendas'), ('gastos_envios', 'Gastos de Envíos Adicionales'), ('gastos_administracion', 'Gastos de Administración'), ('gastos_financieros', 'Gastos Financieros'), ('depreciacion', 'Depreciación del Ejercicio'), ('utilidad_no_operacional', 'Utilidad (pérd.) No Operacional'), ('ajuste_monetario', 'Ajuste Monetario'), ('impuesto_renta', 'Impuesto a la Renta'), ('ajustes', 'Ajustes')], max_length=64)),
                ('valor', models.IntegerField()),
            ],
            options={
                'unique_together': {('mes', 'concepto')},
            },
        ),
    ]
