# Generated by Django 5.2.1 on 2025-02-03 21:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronz_app', '0012_resultadomensualdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Identificación
                ('order_name', models.CharField(db_index=True, max_length=50, verbose_name='Número de Orden')),
                ('shopify_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID Shopify')),
                # Cliente
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre Cliente')),
                ('email', models.EmailField(blank=True, default='', max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('accepts_marketing', models.BooleanField(default=False, verbose_name='Acepta Marketing')),
                # Estados
                ('financial_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partially_paid', 'Parcialmente Pagado'), ('refunded', 'Reembolsado'), ('voided', 'Anulado'), ('', 'Sin estado')], default='', max_length=30, verbose_name='Estado Financiero')),
                ('fulfillment_status', models.CharField(blank=True, choices=[('fulfilled', 'Cumplido'), ('unfulfilled', 'No Cumplido'), ('partial', 'Parcial'), ('', 'Sin estado')], default='', max_length=30, verbose_name='Estado de Cumplimiento')),
                # Fechas
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Creación')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cumplimiento')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                # Montos
                ('currency', models.CharField(default='CLP', max_length=10, verbose_name='Moneda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Envío')),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                # Descuentos
                ('discount_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Descuento')),
                # Envío
                ('shipping_method', models.CharField(blank=True, default='', max_length=200, verbose_name='Método de Envío')),
                # Line Item
                ('lineitem_quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('lineitem_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre Producto')),
                ('lineitem_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio Producto')),
                ('lineitem_compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio Comparación')),
                ('lineitem_sku', models.CharField(blank=True, default='', max_length=50, verbose_name='SKU Producto')),
                ('lineitem_requires_shipping', models.BooleanField(default=True, verbose_name='Requiere Envío')),
                ('lineitem_taxable', models.BooleanField(default=False, verbose_name='Gravable')),
                ('lineitem_fulfillment_status', models.CharField(blank=True, default='', max_length=30, verbose_name='Estado Cumplimiento Producto')),
                ('lineitem_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Descuento Línea')),
                # Dirección Facturación
                ('billing_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre Facturación')),
                ('billing_street', models.CharField(blank=True, default='', max_length=300, verbose_name='Calle Facturación')),
                ('billing_address1', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección 1 Facturación')),
                ('billing_address2', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección 2 Facturación')),
                ('billing_company', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa Facturación')),
                ('billing_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad Facturación')),
                ('billing_zip', models.CharField(blank=True, default='', max_length=20, verbose_name='Código Postal Facturación')),
                ('billing_province', models.CharField(blank=True, default='', max_length=50, verbose_name='Provincia Facturación')),
                ('billing_province_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Provincia Facturación')),
                ('billing_country', models.CharField(blank=True, default='', max_length=10, verbose_name='País Facturación')),
                ('billing_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono Facturación')),
                # Dirección Envío
                ('shipping_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre Envío')),
                ('shipping_street', models.CharField(blank=True, default='', max_length=300, verbose_name='Calle Envío')),
                ('shipping_address1', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección 1 Envío')),
                ('shipping_address2', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección 2 Envío')),
                ('shipping_company', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa Envío')),
                ('shipping_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad Envío')),
                ('shipping_zip', models.CharField(blank=True, default='', max_length=20, verbose_name='Código Postal Envío')),
                ('shipping_province', models.CharField(blank=True, default='', max_length=50, verbose_name='Provincia Envío')),
                ('shipping_province_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Provincia Envío')),
                ('shipping_country', models.CharField(blank=True, default='', max_length=10, verbose_name='País Envío')),
                ('shipping_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono Envío')),
                # Pago
                ('payment_method', models.CharField(blank=True, default='', max_length=100, verbose_name='Método de Pago')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200, verbose_name='Referencia de Pago')),
                ('payment_id', models.CharField(blank=True, default='', max_length=200, verbose_name='ID de Pago')),
                ('payment_references', models.TextField(blank=True, default='', verbose_name='Referencias de Pago')),
                # Reembolsos
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Reembolsado')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Saldo Pendiente')),
                # Otros
                ('vendor', models.CharField(blank=True, default='', max_length=100, verbose_name='Vendedor')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='Etiquetas')),
                ('risk_level', models.CharField(blank=True, default='', max_length=20, verbose_name='Nivel de Riesgo')),
                ('source', models.CharField(blank=True, default='', max_length=50, verbose_name='Fuente')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('note_attributes', models.TextField(blank=True, default='', verbose_name='Atributos de Notas')),
                # Empleado y ubicación
                ('employee', models.CharField(blank=True, default='', max_length=100, verbose_name='Empleado')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Ubicación')),
                ('device_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID de Dispositivo')),
                # Impuestos
                ('tax_1_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Impuesto 1 Nombre')),
                ('tax_1_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuesto 1 Valor')),
                ('tax_2_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Impuesto 2 Nombre')),
                ('tax_2_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuesto 2 Valor')),
                ('tax_3_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Impuesto 3 Nombre')),
                ('tax_3_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuesto 3 Valor')),
                ('tax_4_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Impuesto 4 Nombre')),
                ('tax_4_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuesto 4 Valor')),
                ('tax_5_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Impuesto 5 Nombre')),
                ('tax_5_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuesto 5 Valor')),
                # Términos de pago
                ('payment_terms_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Términos de Pago')),
                ('next_payment_due_at', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Pago')),
                # Otros
                ('receipt_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Recibo')),
                ('duties', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Aranceles')),
                # Metadatos
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Importación')),
            ],
            options={
                'verbose_name': 'Orden Shopify',
                'verbose_name_plural': 'Órdenes Shopify',
                'db_table': 'shopify_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
