# Generated by Django 5.2.1 on 2025-11-11 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bronz_app', '0012_resultadomensualdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Tienda/Bodega')),
            ],
            options={
                'verbose_name': 'Tienda/Bodega',
                'verbose_name_plural': 'Tiendas/Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoRentable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('venta_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('utilidad_bruta_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('margen_bruto', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'productos_rentables',
            },
        ),
        migrations.CreateModel(
            name='EnviosATiendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='bronz_app.catalogo', to_field='sku', verbose_name='SKU')),
                ('tienda_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consult_app.bodegatienda', verbose_name='Tienda/Bodega')),
            ],
            options={
                'verbose_name': 'Envío a Tienda',
                'verbose_name_plural': 'Envíos a Tiendas',
                'db_table': 'envios_a_tiendas',
                'ordering': ['-fecha', 'tienda_bodega'],
            },
        ),
        migrations.CreateModel(
            name='InventarioInicialTiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='bronz_app.catalogo', to_field='sku', verbose_name='SKU')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consult_app.bodegatienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Inventario Inicial Tienda',
                'verbose_name_plural': 'Inventarios Iniciales Tiendas',
                'db_table': 'inventario_inicial_tiendas',
                'ordering': ['-fecha', 'tienda'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('venta_proyectada', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name': 'Proyección de Venta',
                'verbose_name_plural': 'Proyecciones de Ventas',
                'ordering': ['anio', 'mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='AjusteInventarioTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad (±)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_tienda', to='bronz_app.catalogo', to_field='sku', verbose_name='SKU')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='consult_app.bodegatienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Ajuste Inventario Tienda',
                'verbose_name_plural': 'Ajustes Inventario Tienda',
                'db_table': 'ajustes_inventario_tiendas',
                'ordering': ['-fecha', 'tienda', 'sku'],
                'indexes': [models.Index(fields=['tienda', 'sku', 'fecha'], name='idx_ajustes_tsf')],
            },
        ),
    ]
